version: "3.9"

services:
  mariadb:
    image: mariadb:10.6
    restart: "always"
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_DATABASE=${DB_NAME}

  adminer:
    image: adminer
    restart: "always"
    ports:
      - 8081:8080

  tomcat:
    build: .
    ports:
      - ${APP_PORT}:8080
    depends_on:
      - mariadb
    restart: "always"
    links:
      - mariadb
    environment:
      - DB_HOST=mariadb
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

volumes:
  database:
